### ISSUE TITLE
feat: pass directory to open terminal in

### ISSUE THREAD

**Issue by aarondill** [CRAG666/betterTerm.nvim#12]
this would allow the user to detect the project root and open a terminal automatically there.

```lua
require('betterTerm').open(1, { cwd = "<ROOT DIR>" })
```

this could be implemented by calling `lcd DIR` before `term`, after creating the window with `<pos> new`.

**Comment by CRAG666** [comment]
@aarondill pleace send PR

**Comment by aarondill** [comment]
@CRAG666 Please see #13
