### ISSUE TITLE
Terminal stays in background after :q

### ISSUE THREAD

**Issue by comiluv** [CRAG666/betterTerm.nvim#4]
* Description
If the user opens a new terminal and ```:q``` to close the terminal, the terminal isn't removed completely

* Steps to repro
1. Press the hotkey mapped to ```require('betterTerm').select```
2. See "Empty betterTerm's" message
3. Open a terminal by pressing a hotkey mapped to ```require('betterTerm').open```
4. Close the terminal by ```:q```
5. Press the hotkey mapped to ```require('betterTerm').select```
6. See the closed terminal is still available

* Expected
Closed terminal is completely removed from memory

* Environment
Windows 11 22H2
NVIM v0.8.3
Windows Terminal

**Comment by CRAG666** [comment]
I followed the steps and I don't have that problem
