### ISSUE TITLE
Integrating with code_runner.nvim gives error after first run

### ISSUE THREAD

**Issue by comiluv** [CRAG666/betterTerm.nvim#5]
* Description
If the user runs a code with code_runner.nvim, it works first time but fails thereafter.
* Steps to repro
1. Setup hotkeys as described in https://github.com/CRAG666/betterTerm.nvim#integration-with-code_runnernvim
2. Make a simple python script such as below:
```python
print("hello")
```
3. Run above code using the hotkey set up in step 1
4. A terminal will open and "hello" is printed
5. Type ```exit``` in terminal to kill the terminal
6. Repeat step 3
7. See error message:
```
E5108: Error executing lua: .../Local/nvim-data/lazy/betterTerm.nvim/lua/betterTerm.lua:204: E900: Invalid channel id
stack traceback:
        [C]: in function 'nvim_chan_send'
        .../Local/nvim-data/lazy/betterTerm.nvim/lua/betterTerm.lua:204: in function 'send'
        ...rs/choij/AppData/Local/nvim/after/plugin/code_runner.lua:17: in function <...rs/choij/AppData/Local/nvim/afte                                                                                                                                                      r/plugin/code_runner.lua:16>
```
* Expected
"hello" is printed
* Environment
Windows 11 22H2
NVIM 0.8.3
Windows Terminal

**Comment by CRAG666** [comment]
Pleace read README
